---
- hosts: 172.17.0.2
  remote_user: ubuntu
  become: yes
  become_user: root

  # sample tasks to ensure things *just work*
  tasks:

    # set hostname
    - name: set hostname
      hostname: name='smalldatafierce-vm'

